<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://au.edu.swin.waaArtifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://au.edu.swin.waa" xmlns:wsdl1="http://waa.swin.edu.au" name="BookServiceBPELArtifacts" targetNamespace="http://au.edu.swin.waaArtifacts" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <plnk:partnerLinkType name="BookPLT">
    <plnk:role name="BookDetailProvider" portType="wsdl:BookBPELPortType"/>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="BookDetailPLT">
    <plnk:role name="BookProvider" portType="wsdl:BookBPELPortType"/>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="getBookPLT">
    <plnk:role name="BookInfoProvider" portType="wsdl1:Ass02BookSoapPortType"/>
  </plnk:partnerLinkType>
  <import location="BookBPEL.wsdl" namespace="http://au.edu.swin.waa"/>
  <import location="Ass02BookSoap.wsdl" namespace="http://waa.swin.edu.au"/>
</definitions>
